language: objective-c
cache: cocoapods
osx_image: xcode7.3

before_install:
- gem install xcov --no-ri --no-rdoc --no-document
- gem update fastlane --no-ri --no-rdoc --no-document

script: travis/script.sh
after_success: travis/after_success_script.sh


#script:
#- set -o pipefail
#- xcodebuild clean test -workspace OpenFood.xcworkspace -scheme OpenFood -sdk iphonesimulator | xcpretty