require 'securerandom'

default_platform :ios

platform :ios do
before_all do
#ensure_git_status_clean
cocoapods
end

desc "Run tests"
lane :test do
scan(
scheme: "OpenFood",
workspace: "OpenFood.xcworkspace",
clean: true,
code_coverage: true,
skip_slack: true,
sdk: "iphonesimulator9.3"
)
end

desc "Calculate test code coverage score. Need to run test beforehand."
lane :report_test_coverage do
xcov(
workspace: "OpenFood.xcworkspace",
scheme: "OpenFood",
output_directory: "xcov_output"
)
end


desc "Submit a new beta build to App Store"
lane :beta do


create_keychain(
name: ENV["KEYCHAIN_NAME"],
default_keychain: true,
unlock: true,
timeout: 3600,
lock_when_sleeps: true,
password: SecureRandom.base64
)

#Import distribution certificate
import_certificate(
certificate_path: "fastlane/cert/iosDeveloper.p12",
certificate_password: ENV["KEY_PASSWORD"],
keychain_name: ENV["KEYCHAIN_NAME"]
)

import_certificate(
certificate_path: "fastlane/cert/iosDistribution.p12",
certificate_password: ENV["KEY_PASSWORD"],
keychain_name: ENV["KEYCHAIN_NAME"]
)

#Fetch provisioning profile
sigh(
adhoc: false,
username: "guitarslacker@gmail.com",
cert_id: "38CJ7RTF4Q"
)

#increment_build_number

#build
gym(
scheme: "OpenFood",
configuration: "App Store",
sdk: "iphoneos9.3",
clean: true,
include_bitcode: false,
include_symbols: true,
use_legacy_build_api: true,
#export_method: "enterprise"
)

delete_keychain(name: ENV["KEYCHAIN_NAME"])

end

lane :screenshot do
snapshot
frameit
end

end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
