# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

default_platform :ios

platform :ios do
#before_all do
#cocoapods
#end

desc "Run tests"
lane :test do
scan(
scheme: "OpenFood",
workspace: "OpenFood.xcworkspace",
clean: true,
code_coverage: true,
skip_slack: true,
sdk: "iphonesimulator9.3"
)
end

desc "Calculate test code coverage score. Need to run test beforehand."
lane :report_test_coverage do
xcov(
workspace: "OpenFood.xcworkspace",
scheme: "OpenFood",
output_directory: "xcov_output"
)
end


desc "Submit a new beta build to App Store"
lane :beta do

keychain_name = "OpenFood-certs"

create_keychain(
name: keychain_name,
default_keychain: true,
unlock: true,
timeout: 3600,
lock_when_sleeps: true,
password: SecureRandom.base64
)

#Import distribution certificate
import_certificate(
certificate_path: "./fastlane/cert/iosDistribution.p12",
certificate_password: ENV["KEY_PASSWORD"],
keychain_name: keychain_name
)

#Fetch provisioning profile
sigh(
adhoc: false,
username: "guitarslacker@gmail.com",
cert_id: "38CJ7RTF4Q"
)

increment_build_number(build_number: number_of_commits)

#build
gym(
scheme: "OpenFood",
configuration: "App Store",
sdk: "iphoneos9.3",
clean: true,
include_bitcode: false,
include_symbols: true,
use_legacy_build_api: true,
#export_method: "enterprise"
)

delete_keychain(name: keychain_name)

end

lane :screenshot do
snapshot
frameit
end

end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
