# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.49.0"

default_platform :ios


platform :ios do
#before_all do
#cocoapods
#end

desc "Run tests"
lane :test do
scan(
scheme: "OpenFood",
workspace: "OpenFood.xcworkspace",
clean: true,
code_coverage: true,
skip_slack: true,
sdk: "iphonesimulator",
destination: "name-iPhone6"
)
end

desc "Calculate test code coverage score. Need to run test beforehand."
lane :report_test_coverage do
xcov(
workspace: "OpenFood.xcworkspace",
scheme: "OpenFood"
output_directory: "xcov_output"
)
end



lane :beta do
cert
sigh(force: true)
end

lane :screenshot do
snapshot
frameit
end

lane :deliver do
deliver
end

end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
