# Uncomment the lines below you want to change by removing the # in the beginning

devices([
#"iPhone 6",
#"iPhone 6 Plus",
#"iPhone 5",
#"iPhone 4s",
#"iPad Retina"
#"iPad Pro"
])

languages([
"en-US"
#"de-DE",
#"it-IT"
])

# The name of the scheme which contains the UI Tests
scheme "Snapshot"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./OpenFood.xcworkspace"

# For more information about all available options run
# snapshot --help
